- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Login to Docker private registry
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"

- name: Run application containers
  community.docker.docker_container:
    name: "{{ container_base_name }}{{ item }}"
    image: "{{ image_name }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ container_host_port + item - 1 }}:{{ container_port }}"
  loop: "{{ range(1, container_count + 1) | list }}"

- name: Generate Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Restart Nginx to apply new configuration
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

