apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (dict "auths" (dict .Values.dockerRegistry.registry (dict "username" .Values.dockerRegistry.username "password" .Values.dockerRegistry.password "auth" (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc)))) | toJson | b64enc }}

